### ISSUE TITLE
Is there a concept of merging branches?

### ISSUE THREAD

**Issue by hpfast** [Oslandia/qgis-versioning#8]
Hi, nice work!

Is there a concept of merging branches back together? There doesn't seem to be a user interface for it.

**Comment by vmora** [comment]
On update, if you have conflicts, at table is created with
'yours'/'theirs' layer and the deletion of the entry in the table/layer
causes a trigger to reconcile changes.

/!\
  - The conflict table is not loaded automatically if it has no
geometry, you have to load it yourself
  - On deletion on one conflict row (theirs or yours), both rows are
deleted from the conflict (because you solve it by choosing) but qgis
does not update the table (you have to close/re-open to see that the
other entry is removed from the conflict table)

This mechanism could be used to merge branches, but I don't think there
is an interface for that at the moment.

I am tempted to think that modifiying the initial_revision table to give
the origin of the branch would generate a diff that could be applyied to
the origin (merge).

This is untested, so try that with on a db that you don't care about,
but I think it's worth trying.

**Comment by hpfast** [comment]
Thanks for the pointers! I'll look into that when I have time.

On Tuesday, July 7, 2015, Vincent Mora <notifications@github.com> wrote:
> On update, if you have n., at table is created with
> 'yours'/'theirs' layer and the deletion of the entry in the table/layer
> causes a trigger to reconcile changes.
>
> /!\
> - The conflict table is not loaded automatically if it has no
> geometry, you have to load it yourself
> - On deletion on one conflict row (theirs or yours), both rows are
> deleted from the conflict (k
you solve it by choosing) but qgis
> does not update the table (you have to close/re-open to see that the
> other entry is removed from the conflict table)
>
> This mechanism could be used to merge branches, but I don't think there
> is an interface for that at the moment.
>
> I am tempted to think that modifiying the initial_revision table to give
> the origin of the branch would generate a diff that could be applyied to
> the origin (merge).
>
> This is untested, so try that with on a db that you don't care about,
> but I think it's worth trying.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/wi5zOoLXQQUtQYb-wryxw3ih-hl96BNG-rR7JVrWkEAiHrUOdEUjI-_zfeOXU6xAAWC52YpzRg1khHqNkc_m_3Z9kz5a9SDR-zsab32Z3rmQBuO1dl8JnzKfKQ85A7p-4S5wFG7lorKsWS1lCxoMGFRmogvc8g=s0-d-e1-ft#https://github.com/notifications/beacon/ADfUatRT9HJBIMwFDLsfmgmpTGGhJP2-ks5oa94wgaJpZM4FTeyg.gif
>

**Comment by ymoisan** [comment]
Dumb question maybe : are branches really useful for geodata ?  To me, a history of geodata sets is more akin to, for example, the history of a Wikipedia article : a sequence of edits, information about which is maintained and presented to the user (e.g. "view history" in Wikipedia).  

Are branches a la git, that is temporarily forking the dataset to experiment with it, really useful ?  I can't see myself changing for example the geometry type of a dataset (e.g. polygon to multipolygon) and somehow merge that back in trunk.  Or am I missing some obvious business case ?

**Comment by vmora** [comment]
@ymoisan I have recently encountered use-cases when using GIS in simulation, and using posgres as a backbone for simulation systems (i.e. in this case postgres is not used to "centralize" data). But I globally aggree your point.

@hpfast have you tryied ? If it worked some users may be interested in funcding the development of this feature.

**Comment by SebastienPeillet** [comment]
Project migrated to : https://gitlab.com/Oslandia/qgis/qgis-versioning
